

export const GET_CITIES_PENDING = 'GET_CITIES_PENDING';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILED = 'GET_CITIES_FAILED';



export const UNIT_CELSIUS = 'Metric';
export const UNIT_FARENHEIT = 'Imperial';

export const UNIT_PENDING = 'UNIT_PENDING';
export const UNIT_SUCCESS = 'UNIT_SUCCESS';


export const GET_CURRENT_WEATHER_PENDING = 'GET_CURRENT_WEATHER_PENDING';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';


export const GET_SELECTED_CITY_PENDING = "GET_SELECTED_CITY_PENDING";
export const GET_SELECTED_CITY_SUCCESS = "GET_SELECTED_CITY_SUCCESS";
export const GET_SELECTED_CITY_FAILED = "GET_SELECTED_CITY_FAILED";