export default [
    {
        id: 584502,
        name: 'Abastumani',
        name_en: 'Abastumani',
        name_ka: 'აბასთუმანი',
        country: 'GE',
        coord: {
            lon: 42.845718,
            lat: 41.7075,
        },
    },
    {
        id: 610824,
        name: 'Zugdidi',
        name_en: 'Zugdidi',
        name_ka: 'ზუგდიდი',
        country: 'GE',
        coord: {
            lon: 41.87088,
            lat: 42.508801,
        },
    },
    {
        id: 610864,
        name: 'Zest’aponi',
        name_en: 'Zestaponi',
        name_ka: 'ზესტაფონი',
        country: 'GE',
        coord: {
            lon: 43.052502,
            lat: 42.110001,
        },
    },
    {
        id: 611694,
        name: 'Telavi',
        name_en: 'Telavi',
        name_ka: 'თელავი',
        country: 'GE',
        coord: {
            lon: 45.473148,
            lat: 41.919781,
        },
    },
    {
        id: 611717,
        name: 'Tbilisi',
        name_en: 'Tbilisi',
        name_ka: 'თბილისი',
        country: 'GE',
        coord: {
            lon: 44.833679,
            lat: 41.694111,
        },
    },
    {
        id: 611809,
        name: 'Surami',
        name_en: 'Surami',
        name_ka: 'სურამი',
        country: 'GE',
        coord: {
            lon: 43.555561,
            lat: 42.024311,
        },
    },
    {
        id: 611847,
        name: 'Sokhumi',
        name_en: 'Sukhumi',
        name_ka: 'სოხუმი',
        country: 'GE',
        coord: {
            lon: 41.015278,
            lat: 43.003334,
        },
    },
    {
        id: 612126,
        name: 'Samtredia',
        name_en: 'Samtredia',
        name_ka: 'სამტრედია',
        country: 'GE',
        coord: {
            lon: 42.335171,
            lat: 42.153702,
        },
    },
    {
        id: 612230,
        name: 'Sagarejo',
        name_en: 'Sagarejo',
        name_ka: 'საგარეჯო',
        country: 'GE',
        coord: {
            lon: 45.331478,
            lat: 41.733971,
        },
    },
    {
        id: 612287,
        name: 'Rustavi',
        name_en: 'Rustavi',
        name_ka: 'რუსთავი',
        country: 'GE',
        coord: {
            lon: 44.993229,
            lat: 41.549492,
        },
    },
    {
        id: 612502,
        name: 'Pasanauri',
        name_en: 'Pasanauri',
        name_ka: 'ფასანაური',
        country: 'GE',
        coord: {
            lon: 44.689121,
            lat: 42.350601,
        },
    },
    {
        id: 612592,
        name: 'Oni',
        name_en: 'Oni',
        name_ka: 'ონი',
        country: 'GE',
        coord: {
            lon: 43.442501,
            lat: 42.579441,
        },
    },
    {
        id: 612890,
        name: 'Mtskheta',
        name_en: 'Mtskheta',
        name_ka: 'მცხეთა',
        country: 'GE',
        coord: {
            lon: 44.71875,
            lat: 41.845139,
        },
    },
    {
        id: 612987,
        name: 'Mest’ia',
        name_en: 'Mestia',
        name_ka: 'მესტია',
        country: 'GE',
        coord: {
            lon: 42.727798,
            lat: 43.045811,
        },
    },
    {
        id: 613607,
        name: 'Kutaisi',
        name_en: 'Kutaisi',
        name_ka: 'ქუთაისი',
        country: 'GE',
        coord: {
            lon: 42.699741,
            lat: 42.249611,
        },
    },
    {
        id: 613762,
        name: 'Kobuleti',
        name_en: 'Kobuleti',
        name_ka: 'ქობულეთი',
        country: 'GE',
        coord: {
            lon: 41.77528,
            lat: 41.82,
        },
    },
    {
        id: 613902,
        name: 'Khoni',
        name_en: 'Khoni',
        name_ka: 'ხონი',
        country: 'GE',
        coord: {
            lon: 42.420609,
            lat: 42.322601,
        },
    },
    {
        id: 615403,
        name: 'Borjomi',
        name_en: 'Borjomi',
        name_ka: 'ბორჯომი',
        country: 'GE',
        coord: {
            lon: 43.412842,
            lat: 41.852718,
        },
    },
    {
        id: 615532,
        name: 'Batumi',
        name_en: 'Batumi',
        name_ka: 'ბათუმი',
        country: 'GE',
        coord: {
            lon: 41.635929,
            lat: 41.64159,
        },
    },
    {
        id: 615583,
        name: 'Bak’uriani',
        name_en: 'Bakuriani',
        name_ka: 'ბაკურიანი',
        country: 'GE',
        coord: {
            lon: 43.532501,
            lat: 41.749722,
        },
    },
]